config/routes.rb
Rails.application.routes.draw do

  resources :submitforms
  root :to => "submitforms#index"

end

app/models/servernode.rb
class Servernode < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
#  protect_from_forgery with: :exception
end

app/controllers/submitforms_controller.rb
class SubmitformsController < ApplicationController
  require "rest-client"
  respond_to :html, :js, :json, :xml

  def random_ok_note
  end

  def index
    @servernodes = Servernode.all
    respond_with(@servernodes)
  end

  def new
    @servernode = Servernode.new
  end

  #instantiate a Servenode object on both sides
  def create
    @servernode = Servernode.create(servernode_params)
    p = {:servernode => {:name => params[:servernode][:name],
            :status => params[:servernode][:status]}}
    RestClient.post('http://localhost:3000/servernodes',p)
    redirect_to submitforms_path
  end

  def edit
    @servernode = Servernode.find(params[:id])
  end

  #update properties of nodes => need to update frequently
  def update
    id = params[:id]
    p = {:servernode => {:name => params[:servernode][:name],
      :status=>params[:servernode][:status]}}
    @servernode = Servernode.find(params[:id])
    @servernode.update(servernode_params)
    RestClient.put("http://localhost:3000/servernodes/#{id}",p)
    render :nothing => :true
  end


  private
    def servernode_params
      params.require(:servernode).permit(:name,:status)
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/submitforms_helper.rb
module SubmitformsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Server</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/submitforms/_form.html.erb
<%= simple_form_for @servernode, :url => {:controller => 'submitforms', :action => 'create'},:remote => true do |f|%>
  <%= f.input :name %>
  <%= f.input :status, :collection =>['Available','Occupied','Ready','Dump'],
      as: :radio_buttons %>
  <%= f.submit :class => "btn btn-default"  %>
<%end%>

app/views/submitforms/edit.html.erb
<div class="panel panel-default">

  <div class="panel-heading">
    <h3 class="panel-title">Edit Android Server Node Info</h3>
  </div>

  <div class="panel-body">
    <%= simple_form_for @servernode, :url => submitform_path ,:html => { :class => "form form-horizontal", :method => :put } do|f|%>

  <div class="form-group">
    <div class="col-sm-2">
      <%= f.input :name %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-4">
      <%= f.input :status, :collection =>['Available','Occupied','Ready','Dump'],
        as: :radio_buttons %>
      </div>
    </div>

    <div class ="form-group">
    <div calss ="col-sm-2">
      <%= f.submit "Submit",:class => "btn btn-default" , :disable_with => 'Submiting...'  %>
    </div>
  </div>

  <% end %>

</div>

app/views/submitforms/index.html.erb
<h3>Android Server Node Lists</h3>
<div class="panel panel-default">
  <div class="panel-body">

  <div class="pull-right">
    <%= link_to("Add Server Node", {:controller => 'submitforms', :action => 'new'},:remote => true, :class => "btn btn-danger") %>
  </div>

    <table class="table table-bordered col-md-6">
      <thead style ="background-color: #70DB93 ">
        <tr>
          <td> <strong> ID </strong></td>
          <td> <strong> Server </strong> </td>
          <td> <strong> Status</strong></td>
          <td> <strong> Change Status </strong></td>
        </tr>
      </thead>
      <tbody>
      <% @servernodes.each do |f|%>
      <tr>
        <td> <%= f.id%></td>
        <td> <%= f.name %> </td>
        <td> <%= f.status %> </td>
        <td> <%= link_to("Change Status", edit_submitform_path(f),
              :class => "btn btn-danger btn-sm") %> </td>
      </tr>
      </tbody>
    <% end %>
    </table>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-2" id="task-form" style="display:none;"></div>
</div>

app/views/submitforms/new.html.erb
<div class="panel panel-default">

  <div class="panel-heading">
    <h3 class="panel-title">Android Server Node Setup</h3>
  </div>
  <div class="panel-body">
    <%= simple_form_for @servernode,:url => submitforms_path,:html => { :class => "form form-horizontal" , :method => :post} do|f|%>

    <div class="form-group">
      <div class="col-sm-2">
       <%= f.input :name %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-4">
        <%= f.input :status, :collection =>['Available','Occupied','Dump'],
          as: :radio_buttons %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-2">
        <%= f.submit :class => "btn btn-default"  %>
      </div>
    </div>

    <%end%>

</div>

app/views/submitforms/new.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(350);